# Generated by Django 6.0.2 on 2026-03-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='discount',
        ),
    ]
