# Generated by Django 6.0.2 on 2026-03-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_products',
            field=models.IntegerField(default=0),
        ),
    ]
