# Generated by Django 6.0.2 on 2026-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_region_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
