# Generated by Django 6.0.2 on 2026-03-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_city_slug_alter_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='apps.city'),
            preserve_default=False,
        ),
    ]
