# Generated by Django 6.0.3 on 2026-04-05 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_chat_message_chat_chat_buyer_not_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
