# Generated by Django 6.0.3 on 2026-04-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_announcement_publication'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='chat_buyer_not_seller',
        ),
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_chat_per_announcement_buyer_seller',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='apps.announcement'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('announcement', 'buyer', 'seller')},
        ),
    ]
